default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: solucao4242017
  host: localhost

development:
  <<: *default
  database: curso

test:
  <<: *default
  database: curso

production:
  <<: *default
  database: curso
  username: root
  password: solucao4242017
